services:
  postgres:
    image: postgres:16-alpine
    container_name: fintrack-postgres
    environment:
      POSTGRES_DB: fintrack
      POSTGRES_USER: fintrack
      POSTGRES_PASSWORD: fintrack
    ports:
      - "5432:5432"
    volumes:
      - fintrack-postgres-data:/var/lib/postgresql/data

volumes:
  fintrack-postgres-data:
